# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'AWSAutoScaling'
  pod 'AWSCloudWatch'
  pod 'AWSCognito'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSDynamoDB'
  pod 'AWSEC2'
  pod 'AWSElasticLoadBalancing'
  pod 'AWSIoT'
  pod 'AWSKinesis'
  pod 'AWSLambda'
  pod 'AWSMachineLearning'
  pod 'AWSMobileAnalytics'
  pod 'AWSS3'
  pod 'AWSSES'
  pod 'AWSSimpleDB'
  pod 'AWSSNS'
  pod 'AWSSQS'
  pod 'SDWebImage', '~> 5.0'
  pod 'SDWebImageWebPCoder'
  # other pods
  # Pods for Project
end
